### PR TITLE
engine: add .Clock() sugar

### PR DESCRIPTION
**Pull request by yields**

### CODE REVIEW

**Comment by achille-roussel** [comment]
Do you think thinks should be named something like `StartTimer` or `StartClock`. I'm worried that it may be confusing to have methods called `Timer` and `Time` on the same type.

**Comment by yields** [comment]
@achille-roussel how about this:

```golang
func download() (err error) {
  defer stats.Clock("download").Stop()
  ....
  return
}
```

**Comment by achille-roussel** [comment]
Sounds good to me 👍

**Comment by yields** [comment]
> Fix the example ;)

done, i love you for catching it

**Pull request merged**
